### ISSUE TITLE
Missing pumi function to convert from local cell index within a partition to a global cell index

### ISSUE THREAD

**Issue by dcurreli** [SCOREC/pumiMBBL#1]
In the current implementation, a point (or particle) position is identified by the index of the submesh `isubmesh` and by the local cell index `icell` within that submesh. Some PIC operations require a global cell index `kcell`, ordered along one of the coordinates. E.g.:
`kcell = from_local_to_global_index( isubmesh, icell )`

**Comment by vickyragav95** [comment]
Provided new API to return global cell ID from submesh ID and local cell ID --
`int pumi_global_cell_ID(pumi_mesh_t *pumi_mesh, int isubmesh, int local_cell)`
